// Micro_Projects/React/reactmicroproject/src/Employee.js
import { Component } from "react";



class Employee extends Component{
    constructor(){
        super()
        this.state={
            eid:'',
            empName:'',
            empSalary:'',
            result:'',
            flag:false,
            eidError:'',
            empNameError:'',
            empSalaryError:''
           


        }
        //this.Employee = this.Employee.bind(this);

    }
    // const style = {
    // background: 'url(https://www.bing.com/images/search?view=detailV2&ccid=MPA32ocb&id=C4172E3A2D887946D3C574F2EC0D7AF455BB944A&thid=OIP.MPA32ocb1_oMX7l5lFs-5gHaDC&mediaurl=https%3a%2f%2fcapstoneguide.com%2fwp-content%2fuploads%2f2020%2f05%2femployee.png&exph=227&expw=554&q=employee+management+system+background+images+hd&simid=608050130292520470&FORM=IRPRST&ck=F3A57B49964065D5A73E49EE26CE8903&selectedIndex=3&itb=0&adlt=STRICT);'
    // };
    validateEid = (eid) =>{
        let reg=/^[0-9]+$/;
        if(eid===''){
            return "Eid is Required";
        }
        else if(!reg.test(eid)){
            return "Invalid eid"
        }
        else{
            return null;
        }
    }
    validateempName = (empName) =>{
        let reg=/^[a-zA-Z]+$/;
        if(empName===''){
            return "Emp Name is Required";
        }
        else if(!reg.test(empName)){
            return "Invalid Emp Name"
        }
        else{
            return null;
        }

    }
    validateempSalary = (empSalary) =>{
        let reg=/^[0-9]+$/;
        if(empSalary===''){
            return "Emp Salary is Required";
        }
        else if(!reg.test(empSalary)){
            return "Invalid Emp Salary"
        }
        else{
            return null;
        }
    }
    changeId = (e) =>{
        this.setState({eid:e.target.value})
        let error=this.validateEid(this.state.eid);
        this.setState({eidError:error})
    }
    changeName = (e) =>{
        this.setState({empName:e.target.value})
        let error1=this.validateempName(this.state.empName);
        this.setState({empNameError:error1})
    }
    changeSalary = (e) =>{
        this.setState({empSalary:e.target.value})
        let error2=this.validateempSalary(this.state.empSalary);
        this.setState({empSalaryError:error2})
    }

   
    handleSubmit = (e) =>{
        e.preventDefault();

        let error=this.validateEid(this.state.eid);
        this.setState({eidError:error})

        let error1=this.validateempName(this.state.empName);
        this.setState({empNameError:error1})

        let error2=this.validateempSalary(this.state.empSalary);
        this.setState({empSalaryError:error2})

        if(!error && !error1 && !error2){
            this.setState({flag:true})
        
    }
    }
    render(){
        return(

            <div width="80%" class="container mb-3 mt-3" >
               
                <h1 align="center">EMPLOYEE MANAGEMENT SYSTEM</h1>
                <form class="form-horizontal"> 
                    <div className="form-group">
                <label for="empid"><b>EMPLOYEE ID</b></label>
                <input type="text" class="form-control" value={this.state.eid} onChange={this.changeId}></input>
                <br></br>
                <div><font color='red'><b>{this.state.eidError}</b></font></div>
                </div>
                <br></br>
                <div>
                <label for="empname"><b>EMPLOYEE NAME</b></label>
                <input type="text" class="form-control"value={this.state.empName} onChange={this.changeName}></input>
                </div>
                <br></br>
                
                <div><font color='red'><b>{this.state.empNameError}</b></font></div>
                <br></br>
                <div>
                <label for="empsalary" ><b>EMPLOYEE SALARY</b></label>
                <input type="text" class="form-control" value={this.state.empSalary} onChange={this.changeSalary}></input>
                <br></br>
                </div>
                <div><font color='red'><b>{this.state.empSalaryError}</b></font></div>
                <br></br>
                <button type="submit" className="btn btn-secondary"onClick={this.handleSubmit}>SUBMIT</button> &nbsp;&nbsp;&nbsp;
                
                <button className="btn btn-primary">INSERT</button>&nbsp;&nbsp;&nbsp;
                <button className="btn btn-success" >UPDATE</button>&nbsp;&nbsp;&nbsp;
                <button className="btn btn-danger">DELETE</button>&nbsp;&nbsp;&nbsp;
                <button className="btn btn-warning">FIND</button>&nbsp;&nbsp;&nbsp;
                <button className="btn btn-info">FIND ALL</button>&nbsp;&nbsp;&nbsp;
                
                </form>
                <br></br>
                {this.state.flag ? 
                <table >
                    <tr><th>Employee Id</th><th>Employee Name</th><th>Employee Salary</th></tr>
                    <tr><td>{this.state.eid}</td><td>{this.state.empName}</td><td>{this.state.empSalary}</td></tr>
                   
                </table>
                :''

                }
                

            </div>
        )
    }
}
export default Employee;

// ANGULAR/SpringBoot-EMS/src/app/employee/employee.component.ts
import { Component } from '@angular/core';
import { Employee } from '../../model/Employee';
import { EmployeeServiceService } from '../employee-service.service';

@Component({
  selector: 'app-employee',
  templateUrl: './employee.component.html',
  styleUrl: './employee.component.css'
})
export class EmployeeComponent {

  result:string=""

  employee:Employee
  employeeArr: Employee[] = []; 
  flag:boolean

  constructor(private empService:EmployeeServiceService){
    this.employee=new Employee();
    this.flag=false
  }
  insertEmployee(Data:any){
    this.employee.empId=Data.empId;
    this.employee.empName=Data.empName;
    this.employee.empSalary=Data.empSalary;
    this.employee.department.deptId=Data.deptId;
    this.result=this.empService.insertEmployee(this.employee)

  }

  updateEmployee(Data:any){
    this.employee.empId=Data.empId;
    this.employee.empName=Data.empName;
    this.employee.empSalary=Data.empSalary
    this.employee.department.deptId=Data.deptId;
    this.result=this.empService.updateEmployee(this.employee)

  }

  deleteEmployee(Data:any){
    this.result=this.empService.deleteEmployee(Data.empId)

  }

  findEmployee(Data:any){
    let employee:Employee=this.empService.findEmployee(Data.empId)
    this.result=employee.empId +"   "+ employee.empName +"     "+employee.empSalary+"  "+employee.department.deptId
  }
  
  findAllEmployee(){
    this.employeeArr=this.empService.findAllEmployee()
    this.flag=true
  }

}


<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    </head>
 
    <body>
        <h2 align="center">Employee Management System</h2>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10">
                        <form #EmployeeForm="ngForm">
                                <div class="form-group">
                                    <label for="Employee Id">
                                        Employee Id
                                    </label>
                                    <input type="text"
                                           class="form-control"
                                           name="empId"
                                           #id="ngModel" ngModel
                                           required
                                           pattern="[0-9]+"
                                            />
                                </div>
 
 
                              <div *ngIf="id.touched">
                                 <div *ngIf="id.errors?.['required']">
                                 <b style="color: red;">Employee Id Required.</b>
                                 </div>
                                 <div *ngIf="id.errors?.['pattern']">
                                 <font color="red"><b>Invalid Employee Id.</b></font>
                                 </div>
                              </div>
 
 
                                <div class="form-group">
                                    <label for="Employee Name">
                                        Employee Name
                                    </label>
                                    <input type="text"
                                           class="form-control"
                                           name="empName"
                                           #empName="ngModel" ngModel
                                            required pattern="[a-zA-Z]+" />
                                </div>
                                <div *ngIf="empName.touched">
                                  <div *ngIf="empName.errors?.['required']">
                                  <b style="color: red;">Employee Name Required.</b>
                                  </div>
                                  <div *ngIf="empName.errors?.['pattern']">
                                  <font color="red"><b>Invalid Employee Name.</b></font>
                                  </div>
                               </div>
  

                                <div class="form-group">
                                    <label for="Employee Salary">
                                        Employee Salary
                                    </label>
                                    <input type="text"
                                           class="form-control"
                                           name="empSalary"
                                           #empSalary="ngModel" ngModel
                                           required
                                           pattern="[0-9]+"/>
                                </div>
                                <div *ngIf="empSalary.touched">
                                  <div *ngIf="empSalary.errors?.['required']">
                                  <b style="color: red;">Employee Salary Required.</b>
                                  </div>
                                  <div *ngIf="empSalary.errors?.['pattern']">
                                  <font color="red"><b>Invalid Employee Salary.</b></font>
                                  </div>
                               </div>
                               <div class="form-group">
                                <label for="Department number">
                                    Department Number
                                </label>
                                <input type="text"
                                       class="form-control"
                                       name="deptId"
                                       #deptId="ngModel" ngModel
                                       required
                                       pattern="[0-9]+"/>
                            </div>
                            <div *ngIf="deptId.touched">
                              <div *ngIf="deptId.errors?.['required']">
                              <b style="color: red;">Department number Required.</b>
                              </div>
                              <div *ngIf="deptId.errors?.['pattern']">
                              <font color="red"><b>Invalid Department number.</b></font>
                              </div>
                           </div>

                                                             
                                <button class="btn btn-success" (click)="insertEmployee(EmployeeForm.value)">
                                    Insert
                                </button>
                            &nbsp;&nbsp;
                            
                                <button class="btn btn-primary" (click)="updateEmployee(EmployeeForm.value)">
                                    Update
                                
                                </button>&nbsp;&nbsp;
                                
                                <button class="btn btn-danger" (click)="deleteEmployee(EmployeeForm.value)" >
                                    Delete
                                </button>&nbsp;&nbsp;
                                
                                <button class="btn btn-warning" (click)="findEmployee(EmployeeForm.value)">
                                    Find
                                </button>
                            
                                &nbsp;&nbsp;
                                <button class="btn btn-info" (click)="findAllEmployee()">
                                    Find All
                                </button>
                                
                            </form> 
                        </div>
                    </div>
                </div>
         <br>

      <h2 align="center" ><font color="ggreen">{{result}}</font></h2>

      <div align="center" width="80%">
        <table *ngIf="flag" border="4px solid brown" width="60%">
          <tr><th>Employee Id</th><th>Employee Name</th><th>Employee Salary </th><th>Department ID</th></tr>
          <tr *ngFor="let emp of employeeArr"><td>{{emp.empId}}</td><td>{{emp.empName}}</td><td>{{emp.empSalary}}</td><td>{{emp.department.deptId}}</td></tr>
        </table>

      </div>
       
    </body>
</html>
